### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by betteryourweb** [RyanNielson/laravel-facades#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
<unknown> (/home/administrator/.atom/packages/laravel-facades/lib/laravel-facades.coffee:43:13)
```

**Comment by RyanNielson** [comment]
Instead of re-submitting an already existing issue, perhaps comment on that one or make a pull request. You can view the open issue here: #1. I don't use Atom anymore, so I haven't had a chance to correct this yet.
