### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by basudebpal** [RyanNielson/laravel-facades#4]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\basu\AppData\Local\atom\app-0.177.0\resources\app\src\atom.js:54:11)
<unknown> (C:\Users\basu\.atom\packages\laravel-facades\lib\laravel-facades.coffee:43:13)
```

**Comment by RyanNielson** [comment]
I don't understand why issues with the same titles and description keep getting created. There's an existing issue, feel free to make a pull request.
