### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by semihyilmaz** [RyanNielson/laravel-facades#5]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Semy\AppData\Local\atom\app-0.187.0\resources\app\src\atom.js:54:11)
<unknown> (C:\Users\Semy\.atom\packages\laravel-facades\lib\laravel-facades.coffee:43:13)
```

**Comment by RyanNielson** [comment]
@semihyilmaz THIS ALREADY EXISTS AT #1. Getting tired of these duplicate issues.
